yse_jumper.settings:
  type: config_object
  label: 'YSE Jumper settings'
  mapping:
    jump_field_paths_only:
      type: boolean
      label: 'Require jump nav field to perform path lookups'
    parabundle_toggle:
      type: boolean
      label: 'Whether to exclude (TRUE) or include (FALSE) the selected bundles.'
    excluded_parabundles:
      type: sequence
      label: 'Paragraph types to exclude from parent node path lookup'
      sequence:
        type: string
        label: 'Paragraph bundle'
    selected_parabundles:
      type: sequence
      label: 'Paragraph types for paragraphs parent node path lookup'
      sequence:
        type: string
        label: 'Paragraph bundle'
    selected_nodebundles:
      type: sequence
      label: 'Node types for node path lookup'
      sequence:
        type: string
        label: 'Node bundle'
